nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.saas
      group: PRO_GROUP
      appName: saas
    - optional: false
      dataId: silky.hero.nacos.common
      group: PRO_GROUP