nacosConfig:
  listeners:
    - optional: false
      dataId: silky.hero.nacos.account
      group: DEV_GROUP
      appName: account
    - optional: false
      dataId: silky.hero.nacos.common
      group: DEV_GROUP