rpc:
  token: ypjdYOzNd4FwENJiEARMLWwK0v7QUHPW
registrycenter:
  connectionStrings: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183;127.0.0.1:2184,127.0.0.1:2185,127.0.0.1:2186
  type: Zookeeper
  scheme: Digest
  auth: "silky:pass4W0rd"
distributedCache:
  redis:
    isEnabled: true
    configuration: 127.0.0.1:6379,defaultDatabase=0
gateway:
  jwtSecret: jv1PZkwjLVCEygM7faLLvEhDGWmFqRUW